-- Esquema inicial para Supabase/PostgreSQL
-- Sistema de Gestion de Boletos para Jubilados - Obera
--
-- Pensado para ejecutarse en el SQL Editor de Supabase.
-- Usa auth.users para registro/login y public.profiles para datos internos.

begin;

create extension if not exists pgcrypto;

-- =========================
-- Catalogos y perfiles
-- =========================

create table if not exists public.roles (
  id smallint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  description text,
  created_at timestamptz not null default now(),
  constraint roles_code_check check (code in ('admin', 'supervisor'))
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role_id smallint not null references public.roles(id),
  username text not null unique,
  full_name text not null,
  email text unique,
  active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.beneficiary_statuses (
  code text primary key,
  name text not null,
  description text
);

create table if not exists public.card_statuses (
  code text primary key,
  name text not null,
  description text
);

create table if not exists public.anomaly_types (
  code text primary key,
  name text not null,
  description text
);

create table if not exists public.anomaly_statuses (
  code text primary key,
  name text not null
);

create table if not exists public.incident_priorities (
  code text primary key,
  name text not null,
  sort_order smallint not null unique
);

create table if not exists public.incident_statuses (
  code text primary key,
  name text not null
);

-- =========================
-- Configuracion
-- =========================

create table if not exists public.recharge_policies (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  max_tickets_per_operation integer not null,
  monthly_ticket_quota integer,
  valid_from date not null default current_date,
  valid_until date,
  active boolean not null default true,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint recharge_policies_max_positive check (max_tickets_per_operation > 0),
  constraint recharge_policies_quota_positive check (monthly_ticket_quota is null or monthly_ticket_quota > 0),
  constraint recharge_policies_valid_range check (valid_until is null or valid_until >= valid_from)
);

create unique index if not exists recharge_policies_one_active_idx
  on public.recharge_policies(active)
  where active;

create table if not exists public.transport_lines (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  description text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================
-- Padron, tarjetas y recargas
-- =========================

create table if not exists public.beneficiaries (
  id uuid primary key default gen_random_uuid(),
  legacy_code text unique,
  first_name text not null,
  last_name text not null,
  dni text not null unique,
  birth_date date not null,
  street_address text not null,
  neighborhood text not null,
  city text not null default 'Obera',
  status_code text not null references public.beneficiary_statuses(code) default 'activo',
  available_tickets integer not null default 0,
  enrolled_at date not null default current_date,
  created_by uuid references public.profiles(id),
  updated_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint beneficiaries_dni_digits check (dni ~ '^[0-9]{7,8}$'),
  constraint beneficiaries_available_tickets_nonnegative check (available_tickets >= 0)
);

create index if not exists beneficiaries_name_idx
  on public.beneficiaries(last_name, first_name);

create index if not exists beneficiaries_status_idx
  on public.beneficiaries(status_code);

create table if not exists public.cards (
  id uuid primary key default gen_random_uuid(),
  beneficiary_id uuid not null references public.beneficiaries(id) on delete restrict,
  card_number text unique,
  status_code text not null references public.card_statuses(code) default 'pendiente',
  issued_at date,
  block_reason text,
  replaced_by_card_id uuid references public.cards(id),
  created_by uuid references public.profiles(id),
  updated_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint cards_number_required_when_issued check (
    (status_code = 'pendiente' and card_number is null)
    or (status_code <> 'pendiente' and card_number is not null)
  )
);

create unique index if not exists cards_one_active_per_beneficiary_idx
  on public.cards(beneficiary_id)
  where status_code = 'activa';

create index if not exists cards_beneficiary_idx
  on public.cards(beneficiary_id);

create table if not exists public.card_events (
  id uuid primary key default gen_random_uuid(),
  card_id uuid not null references public.cards(id) on delete cascade,
  event_type text not null,
  reason text,
  performed_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  constraint card_events_type_check check (event_type in ('emitida', 'bloqueada', 'desbloqueada', 'reemplazo_solicitado'))
);

create table if not exists public.recharges (
  id uuid primary key default gen_random_uuid(),
  beneficiary_id uuid not null references public.beneficiaries(id) on delete restrict,
  policy_id uuid not null references public.recharge_policies(id),
  quantity integer not null,
  operator_id uuid not null references public.profiles(id),
  performed_at timestamptz not null default now(),
  notes text,
  created_at timestamptz not null default now(),
  constraint recharges_quantity_positive check (quantity > 0)
);

create index if not exists recharges_beneficiary_performed_idx
  on public.recharges(beneficiary_id, performed_at desc);

create index if not exists recharges_operator_idx
  on public.recharges(operator_id);

-- =========================
-- Operacion: viajes, anomalias e incidentes
-- =========================

create table if not exists public.trips (
  id uuid primary key default gen_random_uuid(),
  line_id uuid not null references public.transport_lines(id) on delete restrict,
  service_date date not null,
  service_time time not null,
  tickets_used integer not null default 0,
  successful_validations integer not null default 0,
  rejected_validations integer not null default 0,
  reported_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint trips_counts_nonnegative check (
    tickets_used >= 0 and successful_validations >= 0 and rejected_validations >= 0
  )
);

create index if not exists trips_date_line_idx
  on public.trips(service_date desc, line_id);

create table if not exists public.anomalies (
  id uuid primary key default gen_random_uuid(),
  beneficiary_id uuid references public.beneficiaries(id) on delete set null,
  card_id uuid references public.cards(id) on delete set null,
  type_code text not null references public.anomaly_types(code),
  status_code text not null references public.anomaly_statuses(code) default 'pendiente',
  detail text not null,
  detected_at timestamptz not null default now(),
  resolved_at timestamptz,
  updated_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint anomalies_resolved_state_check check (
    (status_code in ('resuelta', 'descartada') and resolved_at is not null)
    or (status_code not in ('resuelta', 'descartada'))
  )
);

create index if not exists anomalies_status_detected_idx
  on public.anomalies(status_code, detected_at desc);

create index if not exists anomalies_beneficiary_idx
  on public.anomalies(beneficiary_id);

create table if not exists public.anomaly_observations (
  id uuid primary key default gen_random_uuid(),
  anomaly_id uuid not null references public.anomalies(id) on delete cascade,
  author_id uuid not null references public.profiles(id),
  observation text not null,
  created_at timestamptz not null default now()
);

create index if not exists anomaly_observations_anomaly_idx
  on public.anomaly_observations(anomaly_id, created_at);

create table if not exists public.incidents (
  id uuid primary key default gen_random_uuid(),
  line_id uuid not null references public.transport_lines(id) on delete restrict,
  title text not null,
  description text not null,
  priority_code text not null references public.incident_priorities(code) default 'media',
  status_code text not null references public.incident_statuses(code) default 'abierto',
  responsible_id uuid references public.profiles(id),
  reported_by uuid references public.profiles(id),
  reported_at timestamptz not null default now(),
  closed_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint incidents_closed_state_check check (
    (status_code = 'cerrado' and closed_at is not null)
    or (status_code <> 'cerrado')
  )
);

create index if not exists incidents_status_priority_idx
  on public.incidents(status_code, priority_code, reported_at desc);

create index if not exists incidents_line_idx
  on public.incidents(line_id);

-- =========================
-- Auditoria
-- =========================

create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid references public.profiles(id),
  actor_name text,
  action text not null,
  entity_table text not null,
  entity_id uuid,
  detail text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_created_idx
  on public.audit_logs(created_at desc);

create index if not exists audit_logs_actor_idx
  on public.audit_logs(actor_id, created_at desc);

-- =========================
-- Funciones auxiliares
-- =========================

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select r.code
  from public.profiles p
  join public.roles r on r.id = p.role_id
  where p.id = auth.uid()
    and p.active = true
  limit 1
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_user_role() = 'admin'
$$;

create or replace function public.is_supervisor()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_user_role() = 'supervisor'
$$;

create or replace function public.is_internal_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_user_role() in ('admin', 'supervisor')
$$;

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  default_role_id smallint;
  desired_username text;
begin
  select id into default_role_id from public.roles where code = 'supervisor';

  desired_username := coalesce(
    nullif(new.raw_user_meta_data ->> 'username', ''),
    split_part(new.email, '@', 1),
    'usuario_' || left(new.id::text, 8)
  );

  insert into public.profiles (id, role_id, username, full_name, email, active)
  values (
    new.id,
    default_role_id,
    desired_username,
    coalesce(nullif(new.raw_user_meta_data ->> 'full_name', ''), desired_username),
    new.email,
    false
  );

  return new;
end;
$$;

create or replace function public.protect_profile_role_and_active()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    if new.role_id is distinct from old.role_id or new.active is distinct from old.active then
      raise exception 'Solo un administrador puede modificar rol o estado de activacion.';
    end if;
  end if;

  return new;
end;
$$;

create or replace function public.validate_and_apply_recharge()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  policy_record public.recharge_policies%rowtype;
  month_total integer;
begin
  select *
  into policy_record
  from public.recharge_policies
  where id = new.policy_id
    and active = true
    and valid_from <= new.performed_at::date
    and (valid_until is null or valid_until >= new.performed_at::date);

  if not found then
    raise exception 'La politica de recarga no esta activa o vigente.';
  end if;

  if new.quantity > policy_record.max_tickets_per_operation then
    raise exception 'La recarga supera el maximo de boletos por operacion.';
  end if;

  if policy_record.monthly_ticket_quota is not null then
    select coalesce(sum(quantity), 0)
    into month_total
    from public.recharges
    where beneficiary_id = new.beneficiary_id
      and performed_at >= date_trunc('month', new.performed_at)
      and performed_at < date_trunc('month', new.performed_at) + interval '1 month';

    if month_total + new.quantity > policy_record.monthly_ticket_quota then
      raise exception 'La recarga supera el cupo mensual configurado.';
    end if;
  end if;

  update public.beneficiaries
  set available_tickets = available_tickets + new.quantity,
      updated_at = now(),
      updated_by = new.operator_id
  where id = new.beneficiary_id;

  return new;
end;
$$;

create or replace function public.normalize_anomaly_resolution()
returns trigger
language plpgsql
as $$
begin
  if new.status_code in ('resuelta', 'descartada') and new.resolved_at is null then
    new.resolved_at = now();
  elsif new.status_code not in ('resuelta', 'descartada') then
    new.resolved_at = null;
  end if;

  return new;
end;
$$;

create or replace function public.normalize_incident_closed_at()
returns trigger
language plpgsql
as $$
begin
  if new.status_code = 'cerrado' and new.closed_at is null then
    new.closed_at = now();
  elsif new.status_code <> 'cerrado' then
    new.closed_at = null;
  end if;

  return new;
end;
$$;

create or replace function public.log_audit(
  p_action text,
  p_entity_table text,
  p_entity_id uuid,
  p_detail text,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_name text;
begin
  select full_name into v_actor_name
  from public.profiles
  where id = auth.uid();

  insert into public.audit_logs (
    actor_id,
    actor_name,
    action,
    entity_table,
    entity_id,
    detail,
    metadata
  )
  values (
    auth.uid(),
    coalesce(v_actor_name, 'Sistema'),
    p_action,
    p_entity_table,
    p_entity_id,
    p_detail,
    coalesce(p_metadata, '{}'::jsonb)
  );
end;
$$;

create or replace function public.audit_row_changes()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_action text;
  v_id uuid;
begin
  v_action := tg_table_name || '_' || lower(tg_op);

  if tg_op = 'DELETE' then
    v_id := old.id;
  else
    v_id := new.id;
  end if;

  perform public.log_audit(
    v_action,
    tg_table_name,
    v_id,
    case tg_op
      when 'INSERT' then 'Registro creado'
      when 'UPDATE' then 'Registro actualizado'
      when 'DELETE' then 'Registro eliminado'
    end,
    jsonb_build_object('operation', tg_op)
  );

  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end;
$$;

-- =========================
-- Triggers
-- =========================

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_auth_user();

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at
  before update on public.profiles
  for each row execute function public.touch_updated_at();

drop trigger if exists profiles_protect_role_and_active on public.profiles;
create trigger profiles_protect_role_and_active
  before update on public.profiles
  for each row execute function public.protect_profile_role_and_active();

drop trigger if exists recharge_policies_touch_updated_at on public.recharge_policies;
create trigger recharge_policies_touch_updated_at
  before update on public.recharge_policies
  for each row execute function public.touch_updated_at();

drop trigger if exists transport_lines_touch_updated_at on public.transport_lines;
create trigger transport_lines_touch_updated_at
  before update on public.transport_lines
  for each row execute function public.touch_updated_at();

drop trigger if exists beneficiaries_touch_updated_at on public.beneficiaries;
create trigger beneficiaries_touch_updated_at
  before update on public.beneficiaries
  for each row execute function public.touch_updated_at();

drop trigger if exists cards_touch_updated_at on public.cards;
create trigger cards_touch_updated_at
  before update on public.cards
  for each row execute function public.touch_updated_at();

drop trigger if exists trips_touch_updated_at on public.trips;
create trigger trips_touch_updated_at
  before update on public.trips
  for each row execute function public.touch_updated_at();

drop trigger if exists anomalies_touch_updated_at on public.anomalies;
create trigger anomalies_touch_updated_at
  before update on public.anomalies
  for each row execute function public.touch_updated_at();

drop trigger if exists anomalies_normalize_resolution on public.anomalies;
create trigger anomalies_normalize_resolution
  before insert or update on public.anomalies
  for each row execute function public.normalize_anomaly_resolution();

drop trigger if exists incidents_touch_updated_at on public.incidents;
create trigger incidents_touch_updated_at
  before update on public.incidents
  for each row execute function public.touch_updated_at();

drop trigger if exists incidents_normalize_closed_at on public.incidents;
create trigger incidents_normalize_closed_at
  before insert or update on public.incidents
  for each row execute function public.normalize_incident_closed_at();

drop trigger if exists recharges_validate_and_apply on public.recharges;
create trigger recharges_validate_and_apply
  before insert on public.recharges
  for each row execute function public.validate_and_apply_recharge();

drop trigger if exists audit_beneficiaries_changes on public.beneficiaries;
create trigger audit_beneficiaries_changes
  after insert or update on public.beneficiaries
  for each row execute function public.audit_row_changes();

drop trigger if exists audit_cards_changes on public.cards;
create trigger audit_cards_changes
  after insert or update on public.cards
  for each row execute function public.audit_row_changes();

drop trigger if exists audit_recharges_changes on public.recharges;
create trigger audit_recharges_changes
  after insert on public.recharges
  for each row execute function public.audit_row_changes();

drop trigger if exists audit_anomalies_changes on public.anomalies;
create trigger audit_anomalies_changes
  after insert or update on public.anomalies
  for each row execute function public.audit_row_changes();

drop trigger if exists audit_incidents_changes on public.incidents;
create trigger audit_incidents_changes
  after insert or update on public.incidents
  for each row execute function public.audit_row_changes();

-- =========================
-- Datos iniciales
-- =========================

insert into public.roles (code, name, description) values
  ('admin', 'Administrador', 'Gestiona padron, recargas, tarjetas, configuracion, reportes y auditoria.'),
  ('supervisor', 'Supervisor', 'Consulta padron y gestiona anomalias, incidentes, reportes operativos y auditoria.')
on conflict (code) do update set
  name = excluded.name,
  description = excluded.description;

insert into public.beneficiary_statuses (code, name, description) values
  ('activo', 'Activo', 'Beneficiario habilitado.'),
  ('bloqueado', 'Bloqueado', 'Beneficiario bloqueado administrativamente.'),
  ('baja', 'Baja', 'Beneficiario dado de baja.')
on conflict (code) do update set name = excluded.name, description = excluded.description;

insert into public.card_statuses (code, name, description) values
  ('activa', 'Activa', 'Tarjeta emitida y habilitada.'),
  ('pendiente', 'Pendiente', 'Tarjeta pendiente de emision.'),
  ('bloqueada', 'Bloqueada', 'Tarjeta bloqueada.')
on conflict (code) do update set name = excluded.name, description = excluded.description;

insert into public.anomaly_types (code, name, description) values
  ('uso_duplicado', 'Uso duplicado', 'Validaciones cercanas o incompatibles.'),
  ('intento_fraude', 'Intento de fraude', 'Patron de uso sospechoso.'),
  ('tarjeta_bloqueada_utilizada', 'Tarjeta bloqueada utilizada', 'Intento de validacion con tarjeta bloqueada.'),
  ('error_validacion', 'Error de validacion', 'Falla de validacion del sistema.'),
  ('error_lectura', 'Error de lectura', 'Lectura incompleta o fallida.')
on conflict (code) do update set name = excluded.name, description = excluded.description;

insert into public.anomaly_statuses (code, name) values
  ('pendiente', 'Pendiente'),
  ('en_revision', 'En revision'),
  ('resuelta', 'Resuelta'),
  ('descartada', 'Descartada')
on conflict (code) do update set name = excluded.name;

insert into public.incident_priorities (code, name, sort_order) values
  ('baja', 'Baja', 1),
  ('media', 'Media', 2),
  ('alta', 'Alta', 3)
on conflict (code) do update set name = excluded.name, sort_order = excluded.sort_order;

insert into public.incident_statuses (code, name) values
  ('abierto', 'Abierto'),
  ('cerrado', 'Cerrado')
on conflict (code) do update set name = excluded.name;

insert into public.recharge_policies (
  name,
  max_tickets_per_operation,
  monthly_ticket_quota,
  valid_from,
  active
) values (
  'Politica inicial',
  15,
  null,
  current_date,
  true
)
on conflict do nothing;

insert into public.transport_lines (code, name, description) values
  ('linea_1', 'Linea 1', 'Linea configurada inicialmente desde la aplicacion.'),
  ('linea_2', 'Linea 2', 'Linea configurada inicialmente desde la aplicacion.'),
  ('linea_3', 'Linea 3', 'Linea configurada inicialmente desde la aplicacion.')
on conflict (code) do update set
  name = excluded.name,
  description = excluded.description,
  active = true;

-- =========================
-- Row Level Security
-- =========================

alter table public.roles enable row level security;
alter table public.profiles enable row level security;
alter table public.beneficiary_statuses enable row level security;
alter table public.card_statuses enable row level security;
alter table public.anomaly_types enable row level security;
alter table public.anomaly_statuses enable row level security;
alter table public.incident_priorities enable row level security;
alter table public.incident_statuses enable row level security;
alter table public.recharge_policies enable row level security;
alter table public.transport_lines enable row level security;
alter table public.beneficiaries enable row level security;
alter table public.cards enable row level security;
alter table public.card_events enable row level security;
alter table public.recharges enable row level security;
alter table public.trips enable row level security;
alter table public.anomalies enable row level security;
alter table public.anomaly_observations enable row level security;
alter table public.incidents enable row level security;
alter table public.audit_logs enable row level security;

create policy "roles_select_internal" on public.roles
  for select to authenticated
  using (public.is_internal_user() or id = (select role_id from public.profiles where profiles.id = auth.uid()));

create policy "lookup_statuses_select_internal" on public.beneficiary_statuses
  for select to authenticated using (public.is_internal_user());

create policy "card_statuses_select_internal" on public.card_statuses
  for select to authenticated using (public.is_internal_user());

create policy "anomaly_types_select_internal" on public.anomaly_types
  for select to authenticated using (public.is_internal_user());

create policy "anomaly_statuses_select_internal" on public.anomaly_statuses
  for select to authenticated using (public.is_internal_user());

create policy "incident_priorities_select_internal" on public.incident_priorities
  for select to authenticated using (public.is_internal_user());

create policy "incident_statuses_select_internal" on public.incident_statuses
  for select to authenticated using (public.is_internal_user());

create policy "profiles_select_own_or_internal" on public.profiles
  for select to authenticated
  using (id = auth.uid() or public.is_internal_user());

create policy "profiles_update_own_basic" on public.profiles
  for update to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

create policy "profiles_admin_update" on public.profiles
  for update to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "recharge_policies_select_internal" on public.recharge_policies
  for select to authenticated using (public.is_internal_user());

create policy "recharge_policies_admin_insert" on public.recharge_policies
  for insert to authenticated with check (public.is_admin());

create policy "recharge_policies_admin_update" on public.recharge_policies
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "transport_lines_select_internal" on public.transport_lines
  for select to authenticated using (public.is_internal_user());

create policy "transport_lines_admin_insert" on public.transport_lines
  for insert to authenticated with check (public.is_admin());

create policy "transport_lines_admin_update" on public.transport_lines
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "beneficiaries_select_admin_supervisor" on public.beneficiaries
  for select to authenticated using (public.is_internal_user());

create policy "beneficiaries_admin_insert" on public.beneficiaries
  for insert to authenticated with check (public.is_admin());

create policy "beneficiaries_admin_update" on public.beneficiaries
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "cards_select_admin" on public.cards
  for select to authenticated using (public.is_admin());

create policy "cards_admin_insert" on public.cards
  for insert to authenticated with check (public.is_admin());

create policy "cards_admin_update" on public.cards
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "card_events_select_admin" on public.card_events
  for select to authenticated using (public.is_admin());

create policy "card_events_admin_insert" on public.card_events
  for insert to authenticated with check (public.is_admin());

create policy "recharges_select_admin" on public.recharges
  for select to authenticated using (public.is_admin());

create policy "recharges_admin_insert" on public.recharges
  for insert to authenticated
  with check (public.is_admin() and operator_id = auth.uid());

create policy "trips_select_supervisor" on public.trips
  for select to authenticated using (public.is_supervisor());

create policy "trips_supervisor_insert" on public.trips
  for insert to authenticated with check (public.is_supervisor());

create policy "trips_supervisor_update" on public.trips
  for update to authenticated using (public.is_supervisor()) with check (public.is_supervisor());

create policy "anomalies_select_supervisor" on public.anomalies
  for select to authenticated using (public.is_supervisor());

create policy "anomalies_supervisor_insert" on public.anomalies
  for insert to authenticated with check (public.is_supervisor());

create policy "anomalies_supervisor_update" on public.anomalies
  for update to authenticated using (public.is_supervisor()) with check (public.is_supervisor());

create policy "anomaly_observations_select_supervisor" on public.anomaly_observations
  for select to authenticated using (public.is_supervisor());

create policy "anomaly_observations_supervisor_insert" on public.anomaly_observations
  for insert to authenticated
  with check (public.is_supervisor() and author_id = auth.uid());

create policy "incidents_select_supervisor" on public.incidents
  for select to authenticated using (public.is_supervisor());

create policy "incidents_supervisor_insert" on public.incidents
  for insert to authenticated with check (public.is_supervisor());

create policy "incidents_supervisor_update" on public.incidents
  for update to authenticated using (public.is_supervisor()) with check (public.is_supervisor());

create policy "audit_logs_select_internal" on public.audit_logs
  for select to authenticated using (public.is_internal_user());

-- No se habilitan inserts/updates/deletes directos sobre audit_logs desde clientes.
-- La escritura queda centralizada en funciones security definer y triggers.

commit;
